### ISSUE TITLE
自分で立てたPull Requestが「Review required」と出るせいでmergeできない

### ISSUE THREAD

**Issue by fukasawamoe** [fukasawamoe/yoriyoi#44]
いつもお世話になっております。

- 質問内容・実現したいこと
プルリクエストをマージしたい。
プルリクエスト承認画面でスムーズにマージができるように設定をしたい。
- 現状発生している問題・エラーメッセージ
プルリクエストを行い、マージしようとすると以下のような表示になります
[![Image from Gyazo](https://i.gyazo.com/95090789a67f9840eefdc8a446323cc7.png)](https://gyazo.com/95090789a67f9840eefdc8a446323cc7)
- エラーから考えられる原因
前回コンフリクトやリベースなどを行なった際におそらくブランチの保護設定を変更しました
そのため現在の表示になってしまったかと思われます
- 試したこと
https://qiita.com/sounisi5011/items/eba7cf3ed65973e6edb2
以上の記事を参考にしましたが、Botにレビューしてもらうのであれば根本的な解決にはならないと考えたため、今回issueを作成しました。

files changed で自分でレビューしようとしましたがApproveを選択できなかったため断念しました。
[![Image from Gyazo](https://i.gyazo.com/f5ff58ba7fd55b95410e6c0214be8697.png)](https://gyazo.com/f5ff58ba7fd55b95410e6c0214be8697)

お手数をおかけいたしますが、どうぞよろしくお願いいたします。

**Comment by kenchasonakai** [comment]
> 前回コンフリクトやリベースなどを行なった際におそらくブランチの保護設定を変更しました

設定戻せば解決するのでは... 🤔

**Comment by fukasawamoe** [comment]
ありがとうございます！
おっしゃる通り、設定では...と思い設定を変更して直りました💦
お世話をおかけいたしました🙇‍♀️
